import Foundation
import SwiftMoneyFormatMatrix

// A dev-only tool. Writes the committed golden digests the MoneyFormatStyle golden test reads: one
// portable FNV-1a hash of the engine's output per covered locale. Not part of any library product; run
// with `swift run RecordGoldenDigests` after an intended output change, then commit the result.

let repoRoot = FileManager.default.currentDirectoryPath
let outputPath = "\(repoRoot)/Tests/SwiftMoneyFoundationTests/Generated/GoldenDigests.swift"

let entries = FormatMatrix.coveredLocaleIDs
    .map { (id: $0, digest: FormatMatrix.goldenDigest(forLocale: $0)) }
    .sorted { $0.id < $1.id }

var output = """
// Generated by RecordGoldenDigests. Do not edit by hand.
// Regenerate with: swift run RecordGoldenDigests

// A portable FNV-1a hash of the engine's CLDR-derived output, one per covered locale. The golden test
// fails when a locale's digest drifts from the value committed here.
let goldenDigests: [String: UInt64] = [

"""

for entry in entries {
    output += "    \"\(entry.id)\": 0x\(String(entry.digest, radix: 16)),\n"
}

output += "]\n"

try? FileManager.default.createDirectory(
    atPath: (outputPath as NSString).deletingLastPathComponent,
    withIntermediateDirectories: true
)
try! output.write(toFile: outputPath, atomically: true, encoding: .utf8)
print("Wrote \(entries.count) golden digests to \(outputPath)")
