import Foundation
import SwiftMoneyFormatMatrix

// A dev-only tool. Writes what the MoneyFormatStyle golden test reads: one portable FNV-1a hash of the
// engine's output per covered locale, and the two counts that say how much of the full-name
// presentation the engine carries. Not part of any library product; run with
// `swift run RecordGoldenDigests` after an intended output change, then commit the result.

let repoRoot = FileManager.default.currentDirectoryPath
let outputPath = "\(repoRoot)/Tests/SwiftMoneyFoundationTests/Generated/GoldenDigests.swift"

let entries = FormatMatrix.goldenLocaleIDs
    .map { (id: $0, digest: FormatMatrix.goldenDigest(forLocale: $0)) }
    .sorted { $0.id < $1.id }

var output = """
// Generated by RecordGoldenDigests. Do not edit by hand.
// Regenerate with: swift run RecordGoldenDigests

// A portable FNV-1a hash of the engine's CLDR-derived output, one per covered locale. The golden test
// fails when a locale's digest drifts from the value committed here.
let goldenDigests: [String: UInt64] = [

"""

for entry in entries {
    output += "    \"\(entry.id)\": 0x\(String(entry.digest, radix: 16)),\n"
}

output += """
]

// How many (locale, currency) pairs the engine can name in words, across every covered locale. A
// digest says a locale's output moved; this says whether coverage of it grew or shrank.
let goldenNamedCurrencyTotal = \(FormatMatrix.namedCurrencyTotal)

// How many covered locales name no currency at all. A locale inheriting CLDR's root has the symbols
// and none of the names, which ICU renders the same way, so this is recorded rather than forbidden.
let goldenLocalesNamingNoCurrency = \(FormatMatrix.localesNamingNoCurrency)

"""

try? FileManager.default.createDirectory(
    atPath: (outputPath as NSString).deletingLastPathComponent,
    withIntermediateDirectories: true
)
try! output.write(toFile: outputPath, atomically: true, encoding: .utf8)
print("Wrote \(entries.count) golden digests to \(outputPath)")
