name: Linux build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v6

    - name: Swift version
      run: swift --version

    - name: Build
      run: swift build

    - name: Run tests
      run: swift test --parallel
